name: synced_bloc
description: A bloc that is synced across platform channels.
version: 0.0.1
homepage: https://github.com/mase7569/synced_bloc

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.masel.synced_bloc
        pluginClass: SyncedBlocPlugin
      ios:
        pluginClass: SyncedBlocPlugin
